### ISSUE TITLE
Implement pot exec

### ISSUE THREAD

**Issue by pizzamig** [bsdpot/pot#185]
**Is your feature request related to a problem? Please describe.**
To execute a command inside a pot is to use jexec.

**Describe the feature you'd like to have**
A nice addition to the tool of commands available in pot is to run a pot exec as in jexec.
It allows to use pot framework to run commands inside the pot, like the environment variables.
This command can also be used to send a signal to process (with `kill` or `killall`) from inside the jail.

**Describe potential alternatives or workaround you've considered (if any)**
The current workaround is to use jexec.

Feature suggested by @grembo

**Comment by grembo** [comment]
`pot signal` implementation done in #216 (without having to actually enter the jail/rely on commands inside of it).
