### ISSUE TITLE
[BUG] Imported images has permissions issues

### ISSUE THREAD

**Issue by pizzamig** [bsdpot/pot#233]
**Describe the bug**
Once a pot image is imported there is a subtle difference in permissions. A non root user inside the jail has no permission to read the file system. This cause serious issues in system like nomad, that can only use imported images.

**To Reproduce**
1. Create the `pot` with nginx in it
2. Create a snapshot and export the image
3. Import the image
4. Run this command in the two pot `su -m www -c ls`
5. In the imported image you have a permission denied

**Additional context**
Tested on CURRENT. It seems it started on FreeBSD 13.1, but not confirmed.
Still have to check potential zfs attributes differences between the two datasets

**Comment by grembo** [comment]
Couldn't this be a side effect of #218 ?

Originally I wanted to change /opt/pot to be root-readonly, but then we reduced that to /opt/pot/jail/m (so non-root users could read pots/configs).

So now probably /m has 600 which causes issues for non-root users inside the pot. (I didn't test, but it sounds logical to me).

**Comment by grembo** [comment]
I think if we want to achieve all of these goals (all of which I find reasonable):

1. Make read-only access work for non-root user on the jailhost
2. Protect jailed file-system from unprivileged users on the jailhost
3. Keep reasonable file access permissions of the jailed root

We probably need a different file system structure.

Status quo (path/permissions):
```
/opt/pot/jails/<jailname> 0644
/opt/pot/jails/<jailname>/conf 0644
/opt/pot/jails/<jailname>/m 0600
```

Alternative 1 - move /root deeper in /m:
```
/opt/pot/jails/<jailname> 0644
/opt/pot/jails/<jailname>/conf 0644
/opt/pot/jails/<jailname>/m 0600
/opt/pot/jails/<jailname>/m/r 0644
```

Pro: Not much change, solves all problems
Contra: Path gets longer

Alternative 2 - split jails and configs:
```
/opt/pot/jails 0600
/opt/pot/jails/<jailname> 0644
/opt/pot/jails/<jailname>/m 0644
/opt/pot/confs 0644
/opt/pot/confs/<jailname> 0644
```

Pro: Keeps jail root file system structure unaltered
Contra: ZFS filesystem structure gets complicated, lits of change, upgrade path unclear, image generation unclear

This might still be a good idea, but only as part of reworking images (the way they work right no, a lot of config settings are stored which are actually not necessarily what the consumer of the images wants).

Alternative 3 - do something weird with nullfs mounts and/or symlinks

Pro: Might look smart
Contra: Brittle, weird

@pizzamig Do you have additional ideas?

All things considered, Alternative 1 might be the cleanest option (but still causes pain with images/upgrade paths). 

Another alternative would be to go back to allow all users to read all pots (so even nobody on the jailhost can read all files in pots) - or leave securing /opt/pot up to the user (I *do* like being able to run "pot list" as an unprivileged user, but I prefer to have my pots be more secure in terms of file permissions).

The status quo is bad.

**Comment by grembo** [comment]
Another pragmatic approach would be to introduce a group "pot" and make /opt/pot readable by that group (so users who should be able to read it could be invite to the group)

**Comment by grembo** [comment]
Or, even more pragmatically, simply make /opt/pot 640 owned by root:wheel and assume users who use pot read-only commands might get invited into group wheel anyway.

**Comment by pizzamig** [comment]
So, I verified that the permission to the mountpoint is causing the issue.
Fun fact is that everything after the root mountpoint is denied by any non-root user inside a jail.
The easy fix, that I'm going to commit soon-ish, is to comment out the `_fix_pot_mountpoint_permissions` until we agree on a way to move forward.

A 750 permission on `/opt/pot` with a `pot` group seems the way to go, imho.
It's clean and compatible with other groups permission in FreeBSD (i.e. `video`)
