### ISSUE TITLE
[BUG] spelling error on failed pot prune

### ISSUE THREAD

**Issue by bretton** [bsdpot/pot#239]
**Describe the bug**
When running `pot prune` the error message `pot name is arleady stopping!` has a spelling error for "already".

**To Reproduce**
run `pot prune` right after stopping a nomad job.

**Expected behavior**
Pots are pruned, accurate spelling.

**System configuration - if possible**
pot version: 0.15.3

**Additional context**
I looked for the spelling error in the pot repo but didn't find it. It might be elsewhere.

**Comment by grembo** [comment]
@bretton this was "arleady" fixed as part of https://github.com/bsdpot/pot/commit/ee59f6e37d9dcc3a10b0db838930741e6ea2888d
