### ISSUE TITLE
A Pot collection for Ansible

### ISSUE THREAD

**Issue by zilti** [bsdpot/pot#243]
I mainly don't request a new feature for Pot, but instead I want to advertise for my [zilti/pot](https://galaxy.ansible.com/zilti/pot) Ansible collection. If it's good enough it could maybe be added to the Readme?

It maps the init, de-init, vnet-start, create-base, create-fscomp, create-private-bridge, create, destroy, copy-in, copy-out, mount-in, export-ports, start, stop functionalities to Ansible, and it allows you to run playbooks inside pots. We are about to start to actively use this at my company, and I'll add support for more features either when we need it or on request.

**Comment by grembo** [comment]
Hi @zilti, thanks for sharing. We will look into/play with your Ansible roles and if they work fine (which I assume) we can certainly link them in our README.

**Comment by hny-gd** [comment]
Hi @zilti I will also mention your collection in the next quarterly status report if you want?

**Comment by grembo** [comment]
> I'd be fine with that, yes :)

Hi @zilti,

Merged into README.md, I hope this is what you were looking for.

Thanks again for your contributions.
