### ISSUE TITLE
How to configure allow mount using pot ?

### ISSUE THREAD

**Issue by devosalain** [bsdpot/pot#244]
https://forums.freebsd.org/threads/move-from-plain-jail-etc-jail-conf-to-pot.87179/#post-588579

**Comment by grembo** [comment]
> https://forums.freebsd.org/threads/move-from-plain-jail-etc-jail-conf-to-pot.87179/#post-588579
> Where do i put "allow.mount" configs for the jail is not clear from this link for me.

```
bin/pot info -p potname
bin/pot set-attr -A mount -V yes -p potname
```

**Comment by zilti** [comment]
It is very confusing how Pot handles such parameters. I am having a similar issue, I am trying to set `allow.raw_sockets`, but it seems impossible. I tried `pot set-attr -A raw_sockets -V yes -p potname` , but all I get as a response to that is "raw_sockets is not a valid attribute".

**Comment by grembo** [comment]
@devosalain Closing as I think this is resolved now. Please re-open if you feel like this hasn't been resolved yet.
