### ISSUE TITLE
[BUG] Pot mount path is broken after importing an image and cloning it

### ISSUE THREAD

**Issue by urosgruber** [bsdpot/pot#257]
**Describe the bug**
After importing and image with the mount point set you end up with a double path and start then fail. I've noticed there is something about fscomp.conf mentioned in the import code that it's unhandled. 

Before I go into what I've done I would like to know the reason of using the full path for the mount point inside of the pot. I've done a few changes in `_mount_dir` and `_pot_mount` so that when issuing

```
pot mount-in -v -p foo -d /usr/local/etc -m /bar/etc
```

store the value in fscomp.conf with the actual value set via the command and then while mounting add prefix on the fly.

This can then help when exporting and importing since the path can stay as it is. I can make a PR with my changes but would like to first understand if that even makes sense and if this long path in fscomp.conf was actually intentional. Btw, I've not done any research for data sets yet, but I would believe it should work the same way. Also this was only tested for pot that is in running state.

The change I did is visible https://github.com/urosgruber/pot/commit/57af9f2ea6377ea2eac43f1ad897042024cc3a91

**Comment by urosgruber** [comment]
@grembo @pizzamig any comments? I'm running the code mentioned here on production and haven't seen any issues. But would love to know more about the reasons for the current implementation.

**Comment by pizzamig** [comment]
This seems a good idea!
Basically injecting the base path in `_pot_mount` should make everything simpler.
Give me some time to test it and found a way to support this breaking change
