### ISSUE TITLE
[BUG] Pot assumes that $POT_GATEWAY is reachable from all jails and acts as syslog server

### ISSUE THREAD

**Issue by Crest** [bsdpot/pot#85]
**Describe the bug**
Pot configures the jail syslogd by adding `*.* @${POT_GATEWAY}:514` to the jails `/etc/syslog.d/pot.conf`. The assumption that `$POT_GATEWAY` is even reachable from jails let alone a usable syslog server is invalid in several cases. As 
`$POT_GATEWAY` has to be an IPv4 address this assumption is incorrect for jails with aliased IPv6 networking. Neither does the documentation state that IPv4 jails have to be able to reach `$POT_GATEWAY`. Only jails on the public bridge can reasonable be expected to be able to reach `$POT_GATEWAY`.     

**To Reproduce**
1. Create the `pot` with this command: 'pot create -v -p v6 -b 12.1 -t single -N alias -i 2a01:234:5678::1'
2. Run this command: 'pot start v6'
3. The pot is now running with a broken syslogd config attempting to forward all messages to an IPv4 address. 

**Expected behavior**
I expect a jail manager to document how it integrates managed jails and for this integration to work with IPv6 and IPv4 alike. Especially if it forwards logs over the network by default. FreeBSD bridges are about as secure as unmanaged switches without further hardening with `-discover $member`, `-learn $member` and `static $member $macaddr`.

**Requested behavior**
Replace the simple assumption that `$POT_GATEWAY` is a suitable recipient for all syslog messages from all jails with dedicated `$POT_SYSLOG` variable and allow jails to override this variable with an attribute. A way to disable this feature would be very useful as would extending this into a list of syslog servers.

**Comment by pizzamig** [comment]
Hi.
`syslogd` forwarding and centralization is partially working and not fully tested. You are 100% right on been unhappy with that.
I'm unsure if "log forwarding" it's a feature that should be managed by the framework, and I'm seriously considering to deprecate and then remove `syslogd` auto configuration entirely.

I can, for sure, implement the `$POT_SYSLOG` and a per-jail override

**Comment by Crest** [comment]
I don't like this feature either because pot is almost flexible enough to take care of it with hooks and flavours if the user wants it. I'm used to treating my jails as fairly full featured userlands, but I can see how this feature would be useful to users who want to treat their jails as locked down application containers.

**Comment by einsibjarni** [comment]
I really need a way to disable syslogd centralization :)
I'm setting up nomad + pot-task-driver so every pot is running without rc scripts. `pot init` overwrites my syslogd_flags on the host for no good reason.

**Comment by grembo** [comment]
@einsibjarni This will be in the next release
